<?php

namespace Morad\BilleterieBundle\Repository;

/**
 * CoordonneesRelaiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordonneesRelaiRepository extends \Doctrine\ORM\EntityRepository
{
}
