morad_billeterie_homepage:
    path:     /
    defaults: { _controller: MoradBilleterieBundle:Home:index }

morad_billeterie_coordonnes:
    path:     /coordonnees/{id}
    defaults : { _controller: MoradBilleterieBundle:Home:coordonnees } 
    requirements:
      id: \d+