morad_billeterie_homepage:
    path:     /
    defaults: { _controller: MoradBilleterieBundle:Home:index }

morad_billeterie_coordonnes:
    path:     /coordonnes
    defaults : { _controller: MoradBilleterieBundle:Home:coordonnes }